# 网络安全行业特征配置文件
# 基于信息安全、数据保护、威胁检测的多维度识别

industry_info:
  id: "cybersecurity"
  name: "网络安全"
  description: "信息安全、数据保护、威胁检测及相关防护技术"
  priority: 7

# L1层：核心关键词 (权重 0.4)
# 直接提及网络安全相关的核心概念
core_keywords:
  security_basic:
    - 网络安全
    - 信息安全
    - 数据安全
    - 系统安全
    - 应用安全
    - 云安全
    - 终端安全
    - 移动安全
    - 物联网安全
    - 工控安全
    - 区块链安全
    - AI安全
    - 隐私保护
    - 数据保护
  
  threat_protection:
    - 威胁检测
    - 威胁情报
    - 入侵检测
    - 入侵防护
    - 恶意软件
    - 病毒防护
    - 木马检测
    - 勒索软件
    - 僵尸网络
    - APT攻击
    - 零日漏洞
    - 网络攻击
    - 黑客攻击
    - 钓鱼攻击
  
  security_management:
    - 安全管理
    - 风险评估
    - 合规审计
    - 安全运营
    - 应急响应
    - 事件响应
    - 灾难恢复
    - 业务连续性
    - 安全培训
    - 安全意识
    - 等级保护
    - 数据分级

# L2层：技术术语 (权重 0.3)
# 网络安全技术相关的专业术语
technical_terms:
  security_tech:
    - 防火墙
    - IDS
    - IPS
    - WAF
    - 入侵检测系统
    - 入侵防护系统
    - Web应用防火墙
    - 下一代防火墙
    - NGFW
    - 统一威胁管理
    - UTM
    - 安全网关
    - VPN
    - SSL
    - TLS
  
  encryption_auth:
    - 加密
    - 解密
    - 数字签名
    - 数字证书
    - 公钥加密
    - 私钥加密
    - 对称加密
    - 非对称加密
    - 哈希算法
    - 身份认证
    - 多因子认证
    - 生物识别
    - 单点登录
    - 访问控制
  
  security_analysis:
    - 漏洞扫描
    - 渗透测试
    - 代码审计
    - 安全测试
    - 威胁建模
    - 风险分析
    - 安全评估
    - 基线检查
    - 配置检查
    - 日志分析
    - 行为分析
    - 异常检测
    - 机器学习
    - 人工智能
  
  compliance_standards:
    - ISO27001
    - 等级保护
    - SOC2
    - PCI-DSS
    - GDPR
    - 数据保护法
    - 网络安全法
    - 密码法
    - 关键信息基础设施
    - 商用密码
    - 国密算法
    - 可信计算

# L3层：应用场景 (权重 0.2)
# 网络安全在各个领域的应用
application_scenarios:
  enterprise_security:
    - 企业安全
    - 办公安全
    - 内网安全
    - 边界安全
    - 终端安全
    - 邮件安全
    - 文档安全
    - 数据库安全
    - 服务器安全
    - 网站安全
    - 应用安全
    - 开发安全
  
  industry_security:
    - 金融安全
    - 政务安全
    - 医疗安全
    - 教育安全
    - 电力安全
    - 交通安全
    - 制造业安全
    - 零售安全
    - 电商安全
    - 互联网安全
    - 运营商安全
    - 能源安全
  
  emerging_security:
    - 云安全
    - 容器安全
    - 微服务安全
    - API安全
    - 移动应用安全
    - 物联网安全
    - 车联网安全
    - 工业互联网安全
    - 5G安全
    - 区块链安全
    - AI安全
    - 量子安全
  
  security_services:
    - 安全托管
    - 安全咨询
    - 渗透测试
    - 安全运营
    - 应急响应
    - 威胁狩猎
    - 安全培训
    - 合规咨询
    - 风险评估
    - 安全审计
    - 数据恢复
    - 取证分析

# L4层：相关实体 (权重 0.1)
# 网络安全产业链相关的公司、产品、平台
related_entities:
  global_security_companies:
    - Symantec
    - McAfee
    - Kaspersky
    - Trend Micro
    - Fortinet
    - Palo Alto Networks
    - Check Point
    - CrowdStrike
    - FireEye
    - Splunk
    - IBM Security
    - Cisco Security
    - Microsoft Security
    - Google Security
    - Amazon Security
  
  chinese_security_companies:
    - 奇安信
    - 深信服
    - 启明星辰
    - 绿盟科技
    - 天融信
    - 山石网科
    - 安恒信息
    - 卫士通
    - 亚信安全
    - 360安全
    - 腾讯安全
    - 阿里安全
    - 华为安全
    - 金山毒霸
    - 瑞星
    - 江民科技
    - 北信源
    - 蓝盾股份
    - 数字认证
    - 格尔软件
  
  security_products:
    - 防火墙
    - 杀毒软件
    - 安全网关
    - 堡垒机
    - 上网行为管理
    - 数据防泄漏
    - DLP
    - 终端检测响应
    - EDR
    - 扩展检测响应
    - XDR
    - 安全信息事件管理
    - SIEM
    - 安全编排自动化响应
    - SOAR
    - 零信任
    - ZTNA
  
  certification_standards:
    - CC认证
    - FIPS认证
    - 商密认证
    - 等保测评
    - 风险评估
    - 渗透测试
    - 安全审计
    - ISO27001
    - CISSP
    - CISA
    - CISM
    - CEH
    - OSCP
    - CISSP
    - "CCSP"

# 特殊匹配规则
special_rules:
  # 排除词汇：避免误判
  exclude_keywords:
    - 网络安全概念股
    - 网络安全板块
    - 炒股
    - 股价
    - 社会安全
    - 人身安全
    - 食品安全
    - 交通安全
    - 生产安全
  
  # 必须配对出现的词汇
  required_pairs:
    - ["网络", "安全"]
    - ["信息", "安全"]
    - ["数据", "安全"]
    - ["威胁", "检测"]
    - ["漏洞", "扫描"]
  
  # 上下文增强
  context_boost:
    - 网络攻击
    - 数据泄露
    - 隐私保护
    - 合规要求
    - 风险管控
    - 安全防护
    - 威胁防范
    - 应急处置
    - 技术对抗
    - 安全建设
    - 防护体系
    - 监测预警
    - 态势感知
    - 协同防御
    - 主动防御
    - 纵深防御