# 行业匹配系统主配置文件
# 定义全局参数和行业列表

# 系统版本信息
version: "1.0.0"
description: "全自动行业识别匹配系统"

# 启用的行业列表 - 全部39个行业
enabled_industries:
  # 科技类行业 (10个)
  - ai                    # 人工智能
  - semiconductor         # 半导体
  - gaming               # 游戏
  - fintech              # 金融科技
  - cloud_computing      # 云计算
  - saas                 # SaaS
  - cybersecurity        # 网络安全
  - iot                  # 物联网
  - 5g_communication     # 5G通信
  - robotics             # 机器人
  
  # 新兴热门行业 (8个)
  - smart_manufacturing  # 智能制造
  - commercial_space     # 商业航天
  - aigc                 # AIGC
  - autonomous_driving   # 智能驾驶
  - biotechnology        # 生物医药
  - medical_devices      # 医疗器械
  - new_materials        # 新材料
  - agricultural_technology  # 农业科技
  
  # 传统产业 (8个)
  - automotive_manufacturing  # 汽车制造
  - new_energy_vehicles      # 新能源汽车
  - renewable_energy         # 新能源
  - real_estate             # 房地产
  - construction_engineering # 建筑工程
  - steel_metallurgy        # 钢铁冶金
  - petrochemicals          # 石油化工
  - textile_apparel         # 纺织服装
  
  # 服务业 (13个)
  - ecommerce               # 电子商务
  - cross_border_ecommerce  # 跨境电商
  - logistics_express       # 物流快递
  - online_education        # 在线教育
  - tourism_hotels          # 旅游酒店
  - retail_consumer         # 零售消费
  - idc_data_center         # IDC数据中心
  - short_video_live_streaming  # 短视频直播
  - local_life_services     # 本地生活服务
  - healthcare              # 大健康
  - content_creation        # 内容创作
  - enterprise_services     # 企业服务
  - cultural_creative       # 文化创意

# 匹配算法参数
matching_config:
  # 权重配置 - 四层评分体系
  layer_weights:
    core_keywords: 0.4      # L1: 核心关键词权重
    technical_terms: 0.3    # L2: 技术术语权重
    application_scenarios: 0.2  # L3: 应用场景权重
    related_entities: 0.1   # L4: 相关实体权重
  
  # 置信度阈值
  thresholds:
    high_confidence: 0.3    # 直接匹配阈值
    low_confidence: 0.15    # 最低匹配阈值
    fuzzy_similarity: 0.85  # 模糊匹配相似度阈值
  
  # 匹配参数
  parameters:
    min_keyword_frequency: 1         # 关键词最少出现次数
    max_industries_per_article: 3    # 每篇文章最多匹配行业数
    context_window_size: 50          # 上下文窗口大小（词数）
    boost_factor_nearby: 1.2         # 相邻关键词加权因子
    boost_factor_cluster: 1.5        # 关键词聚集加权因子

# 性能配置
performance:
  batch_size: 10             # 批处理大小 - 小批次快速反馈
  max_workers: 3             # 最大线程数 - 保持稳定性
  timeout_seconds: 18000     # 超时时间（5小时）
  cache_enabled: true        # 是否启用缓存

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file_pattern: "industry_matching_{timestamp}.log"
  
# 数据库配置
database:
  table_name: "news_items"
  industry_field: "industries"
  batch_update_size: 100